#!/usr/bin/python

# SetWall - Wallpaper manager
# 
# Copyright (C) 2014  Cristian Andrei Calin <cristian.calin@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import dbus
import sys
import os
from gi.repository import GObject as gobject

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from wpm.application import *

# main function call creates application object and starts processing
if __name__ == "__main__":
  # allow other threads to execute
  dbus.glib.init_threads()
  gobject.threads_init()

  app = application()
  app.main()

  sys.exit(0)
