#!/usr/bin/python

# SetWall - Wallpaper manager
# 
# Copyright (C) 2014  Cristian Andrei Calin <cristian.calin@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import dbus
import dbus.service
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from wpm.application import *

# Import global constants
from wpm.globals import *

if __name__ == '__main__':
  try:
    session_bus = dbus.SessionBus()
    session_obj = session_bus.get_object(
      "%s.%s" % (BASE_ID, APP_NAME),
      "%s/%s" % (APP_PATH, APP_NAME)
    )
    if len(sys.argv) == 2:
      exec "result = session_obj.%s()" % sys.argv[1]
      if result is not None:
        print result
    elif len(sys.argv) > 2:
      exec "session_obj.%s(\"%s\")" % (sys.argv[1], "\",\"".join(sys.argv[2:]))
  except dbus.DBusException as e:
    print "%s could not be contacted" % APP_FRIENDLY_NAME
    print e
    exit(1)
